name: npm run ve:Equal

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # 12:00 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git checkout HEAD^
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm run ve:Equal
      - name: Commit changes
        run: |
          git config --global user.email "oxSaturn@proton.me"
          git config --global user.name "oxSaturn"
          git add .
          git commit -m "Run ve:Equal"
          git push
